AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function for organiser-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  OrganiserServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: "organiserservicefunction:java11-maven-v1"
      PackageType: "Image"
      Events:
        Events:
          CreateOrganiser:
            Type: Api
            Properties:
              Path: /v1/organisers/{id}
              Method: post
          ReadOrganiser:
            Type: Api
            Properties:
              Path: /v1/organisers/{id}
              Method: get
          DeleteOrganiser:
            Type: Api
            Properties:
              Path: /v1/organisers/{id}
              Method: delete
          UpdateOrganiser:
            Type: Api
            Properties:
              Path: /v1/organisers/{id}
              Method: put
    Metadata:
      DockerTag: java11-maven-v1
      DockerContext: ./OrganiserServiceFunction
      Dockerfile: Dockerfile
